### ISSUE TITLE
How to run charlet?

### ISSUE THREAD

**Issue by jhagenauer** [amzn/chalet-charging-location-for-electric-trucks#1]
The README file says to run the charlet file to execute it. But this file does not exist. Where can I find it? What am I doing wrong? Thank you.

**Comment by ghost** [comment]
I think you mean 'chalet' as cmd. Did you fulfill the requirements and did you run all the pip install cmd's?

**Comment by jhagenauer** [comment]
Yes. I ran the pip install cmd's. Where can I find the executable of charlet? At which point is it built?

**Comment by jhlamzn** [comment]
Hello,

After successful installation the 'chalet' command is available in the root directory. The associated file is in the bin/ directory of the virtual environment, that would be venv/bin/chalet following the README. The environment needs to be activated when running installation commands and running the tool itself.

Does this resolve the issue?

**Comment by jhagenauer** [comment]
Hello,

no, the charlet comman is not avaible in my root directory. I am running windows 10. What do you mean by 'root directory'? 
Anyhow, I searched the whole system for the file 'charlet'. No success. 

These are the last lines of the output of the command python -m pip install -e .[testing]

```
Successfully built chalet
Installing collected packages: iniconfig, exceptiongroup, coverage, pytest, pyte
st-cov, chalet
  Attempting uninstall: chalet
    Found existing installation: chalet 1.0
    Uninstalling chalet-1.0:
      Successfully uninstalled chalet-1.0
Successfully installed chalet-1.0 coverage-7.3.1 exceptiongroup-1.1.3 iniconfig-
2.0.0 pytest-7.4.2 pytest-cov-4.1.0
```

**Comment by jhlamzn** [comment]
By root directory I meant the top level directory of the cloned repository, which would be 'chalet-charging-location-for-electric-trucks' per default. Can you check the contents of your virtual environment subdirectory, i.e. 'chalet-charging-location-for-electric-trucks/venv/bin' ? Please also note that 'chalet' is spelled without 'r'.

**Comment by jhagenauer** [comment]
Hi,

I finally found the chalet.exe file in venv/Scripts. I use windows so that might have caused confusion.

Best
Julian

**Comment by jhlamzn** [comment]
Okay I see, good point. I am closing the issue.
